name: CI on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        make

      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal
