name: CI

on: [push]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build on linux
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        make

      env:
        OPAM_VERSION: 2
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build on mac
      run: |
        brew install make ocaml
       
        # bash -ex .travis-ocaml.sh
        # eval $(opam env)
        make

      # env:
      #   OPAM_VERSION: 2
      #   OCAML_VERSION: 4.11
      #   TRAVIS_OS_NAME: osx
